---
# tasks file for firewall
#
- name: Allow all local ICMP
  vyos_config:
    lines:
      - set firewall all-ping enable
  tags:
    - firewall

- name: Allow stateful traffic
  vyos_config:
    lines:
      - set firewall state-policy established action accept
      - set firewall state-policy related action accept
  tags:
    - firewall
      
- name: address_groups 
  vyos_config:
      src: address_groups.j2
  when:
      - firewall is defined
      - firewall.address_groups is defined
  tags:
      - firewall

- name: network_groups 
  vyos_config:
      src: network_groups.j2
  when:
      - firewall is defined
      - firewall.network_groups is defined
  tags:
      - firewall

- name: v4 firewall rules
  vyos_config:
      src: rules_v4.j2
  when:
      - firewall is defined
      - firewall.ipv4 is defined or firewall.ipv6 is defined
  tags:
      - firewall

- name: v6 firewall rules
  vyos_config:
      src: rules_v6.j2
  when:
      - firewall is defined
      - firewall.ipv4 is defined or firewall.ipv6 is defined
  tags:
      - firewall
